# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

pool:
  vmImage: ubuntu-latest

steps:
- script: cmake --version
  displayName: 'Check cmake version'

- script: g++ --version
  displayName: 'Check g++ version'

- script: python3 --version
  displayName: 'Check Python version'

#Valgrind not yet installed
#- script: valgrind --version
#  displayName: 'Check valgrind version'

- script: |
    ls -l
    pwd
    mkdir build
    cd build
    echo check new directory
    pwd
    ls -l
  displayName: 'Create build directory'

- script: |
    cd build
    pwd
    cmake -D ENABLE_PYTHON_EXAMPLES=OFF -D ENABLE_PYTHON=OFF -D ENABLE_CXX_EXAMPLES=OFF -D MEM_CHECK=OFF ..
  displayName: 'Build'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
