
trigger:
- '*'

pool:
  vmImage: ubuntu-latest

steps:
- script: cmake --version
  displayName: 'Check cmake version'

- script: g++ --version
  displayName: 'Check g++ version'

- script: python3 --version
  displayName: 'Check Python version'

- script: |
    sudo apt-get install valgrind
    valgrind --version
  displayName: install valgrind

- script: |
    mkdir build
  displayName: 'Create build directory'

- script: |
    git submodule init
    git submodule update
    pip3 install numpy
    pip3 install matplotlib
  displayName: 'Add python dependencies'

- script: |
    export PYTHONPATH='$(pwd)/python/lib/site-packages'
    pwd
    echo PYTHONPATH set to $PYTHONPATH
  displayName: 'set PYTHONPATH'

- script: |
    cd build
    cmake -D ENABLE_PYTHON_EXAMPLES=OFF -D ENABLE_PYTHON=ON -D ENABLE_CXX_EXAMPLES=OFF -D MEM_CHECK=OFF ..
    make -j 4
  displayName: 'Build'

- script: |
    cd build
    ctest --verbose
  displayName: 'Test'

- script: |
    cd build
    cmake -D ENABLE_PYTHON_EXAMPLES=OFF -D ENABLE_PYTHON=OFF -D ENABLE_CXX_EXAMPLES=OFF -D MEM_CHECK=ON .
    ctest --verbose
  displayName: 'Memory tests w/ valgrind'
